apiVersion: batch/v1
kind: Job
metadata:
  name: run-kubeflow-pipeline
  namespace: default  
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pipeline-runner
        image: dockerhub:img
        command: ["python", "/app/run_pipeline.py"]
  backoffLimit: 3  