apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-pipeline-runner
  namespace: default
spec:
  project: default
  source:
    repoURL: "https://github.com/zakariaanzid/another-pipeline.git"
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://kns-job-2.jxe.10.132.0.165.nip.io/
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
