apiVersion: v1
kind: Pod
metadata:
  name: cleanup-old-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  containers:
    - name: cleanup
      image: bitnami/kubectl
      command:
        - kubectl
        - delete
        - job
        - run-kubeflow-pipeline
        - -n
        - kubeflow
        - --ignore-not-found
  restartPolicy: Never
