apiVersion: batch/v1
kind: Job
metadata:
  name: run-kubeflow-pipeline
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  selector:
    matchLabels:
      job-name: run-kubeflow-pipeline
  template:
    metadata:
      labels:
        job-name: run-kubeflow-pipeline
    spec:
      restartPolicy: Never
      containers:
      - name: pipeline-runner
        image: zakariaanzid/kbfargo:latest
        command: ["python", "/app/kbf-run.py"]
  backoffLimit: 4
