apiVersion: batch/v1
kind: Job
metadata:
  name: run-kubeflow-pipeline
  namespace: zakaria
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        job-name: run-kubeflow-pipeline
    spec:
      serviceAccountName: default-editor
      automountServiceAccountToken: true
      restartPolicy: Never
      containers:
        - name: pipeline-runner-container
          image: zakariaanzid/kbfargo:latest
          command: [python, /app/kbf-run.py]
          env:
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kfp/token
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi

