apiVersion: batch/v1
kind: Job
metadata:
  name: run-kubeflow-pipeline
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      job-name: run-kubeflow-pipeline
  template:
    metadata:
      labels:
        job-name: run-kubeflow-pipeline
    spec:
      restartPolicy: Never
      initContainers:
      - name: delete-previous-job
        image: bitnami/kubectl:latest
        command: ["sh", "-c", "kubectl delete job run-kubeflow-pipeline -n kubeflow --ignore-not-found"]

      containers:
      - name: pipeline-runner
        image: zakariaanzid/kbfargo:latest
        command: ["python", "/app/kbf-run.py"]
  backoffLimit: 4
