apiVersion: batch/v1
kind: Job
metadata:
  name: run-kubeflow-pipeline
  namespace: kubeflow
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: pipeline-runner
        image: zakariaanzid/kbfargo:latest
        command: ["python", "/app/kbf-run.py"]
  backoffLimit: 4
